name: Test

on:
  workflow_run:
    workflows: [ Build ]
    types: [ completed ]

jobs:
  test:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: make tests_run
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        gcov: true
        gcov_ignore: tests
